### ISSUE TITLE
Battle freezing

### ISSUE THREAD

**Issue by bfcferreira** [jjppof/goldensun_html5#14]
The battles worked fine for me the first few times I tried, and now it just freezes when it reaches Sheba's turn (she's the first to attack). It says she used whatever it is you tell her to do (I used Attack) but then the game just soft locks and doesn't go anywhere. The idle animations still play for everyone though.

**Comment by jjppof** [comment]
Does it soft locks when you start a battle multiple times without refreshing the page?

**Comment by bfcferreira** [comment]
Nope, any time I open it... Whether on my own server or the Demo. Maybe it's Firefox? I can try Chrome

**Comment by jjppof** [comment]
Please try on Chrome. There's a lot of issues related to Firefox.

**Comment by bfcferreira** [comment]
It seems to work correctly on Chrome. Also, I tried again on Firefox and it works correctly now as well. I suppose either something changed or this issue is just inconsistent

**Comment by jjppof** [comment]
Ok, let us keep this open for a while, you aren't the first one to report it.

**Comment by SteveLiGt** [comment]
hi, **jjppof, ( I do not know if you can see this message, if you could, please reply to me when you have a chance)**

first, I would like to appreciate people like you to make this GS engine, although based on our Demo, there still plenty that we could do. A bit about me, I was one of the fan of our GS, and after played the GS Generation 3, I felt the story leftover so much to tell us. And personally, I enjoyed play gen 1st and 2nd much more then gen 3nd. 
For me, the most fancinating part of GS is the mechanism of PSYCHIC AND DINJIN, I was always look for if there is a game like it, but so far, no luck. So I started to wondering if it is possible that we could do something to rebuild even partially of the GS ( **Again, thanks for making the GS engine, it is amazing.)** 
**_I was currently working on Computer science degree on a 4-year school ( I did have some prior programming experience for c and c++, but very little for HTML5 and JavaScript)_**

so I download the HTML5 ( again, not so familiar with it), so I ran it, it gave a web address, when I loaded it in my Chrome, it gave me exactly same web page like the Demo. 
**With all my respect, Is that all we have currently? ( I know you are not going to make the animation or map, but is it possible for people who interested at this to make it by ourselves by making use of what you provided here? If so, where should we get started? Do we need to have some JavaScript in order to do it?  // if so, let me know, I could self-taught some JavaScript during my leisure time.**
