### ISSUE TITLE
Set Max FPS to 60

### ISSUE THREAD

**Issue by bfcferreira** [jjppof/goldensun_html5#154]
When the game runs at above 60FPS, everything slows down (animations, running, etc). Set the max frame rate at 60 to avoid this. (Reproducible in browsers/settings that allow more than 60 FPS)

**Comment by jjppof** [comment]
More than 60 fps? Do you have a screenshot showing this fps? `update` uses [window.requestAnimationFrame()](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) which it refreshes rate "is usually 60 times per second". If it's a custom browser feature, I'm not supporting it.

I expect a lower fps in the firefox browser only, which is a known issue. Due to it, I'm only supporting chromium based browsers.

**Comment by bfcferreira** [comment]
![imagem](https://user-images.githubusercontent.com/69651482/99906617-03975080-2cd0-11eb-9ff5-d2db684d7025.png)
https://gyazo.com/bcbefeb24dc0a939738b74b916fcbc01

**Comment by jjppof** [comment]
It seems that I was wrong about the `requestAnimationFrame`:

> The number of callbacks is usually 60 times per second, but will generally match the display refresh rate in most web browsers as per W3C recommendation.
